# Generated by Django 3.1 on 2023-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='recipe',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='books'),
        ),
    ]
